runtime: nodejs
env: flex

handlers:
  - url: /desktop_pc
    static_dir: /usr/share/nginx/html/desktop_pc

  - url: /planet
    static_dir: /usr/share/nginx/html/planet

  - url: /.*
    static_files: /usr/share/nginx/html/index.html
    upload: /usr/share/nginx/html/index.html