runtime: nodejs
env: flex

handlers:
  - url: /desktop_pc
    static_dir: /usr/share/nginx/html/desktop_pc

  - url: /planet
    static_dir: /usr/share/nginx/html/planet

  - url: /projects
    static_dir: public/projects

  - url: /.*
    script: auto
