steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - 'gcr.io/$PROJECT_ID/my-image:latest'
      - "."

  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/my-image:latest"

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "dogeloveshipster-website"  # Automatically get project ID and append "-website"
      - "--image=gcr.io/$PROJECT_ID/my-image:latest"
      - "--platform=managed"
      - "--region=us-west1"
      - "--allow-unauthenticated"

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - "gcr.io/$PROJECT_ID/my-image:latest"
