steps:
  # Define your build steps here
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/my-image:$COMMIT_SHA"  # Use $COMMIT_SHA as the tag to ensure uniqueness
      - "."
      
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/my-image:$COMMIT_SHA"  # Push the image with the same tag

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - "gcr.io/$PROJECT_ID/my-image:$COMMIT_SHA"  # Reference the image with the COMMIT_SHA tag
