steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "--no-cache"
      - "-t"
      - 'gcr.io/$PROJECT_ID/my-image:$SHORT_SHA'  # Push the image with the "latest" tag
      - "-f"  # Specify the Dockerfile
      - "/home/seregio/website-DogeLovesHipster-1/Dockerfile"  # Use the absolute path to your Dockerfile
      - "."  # Specify the build context (current directory)

  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/my-image:$SHORT_SHA"  # Push the image with the "latest" tag

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - "gcr.io/$PROJECT_ID/my-image:$SHORT_SHA"  # Reference the image with the "latest" tag
