steps:
  # Define your build steps here
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/my-image", "."]

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - "gcr.io/$PROJECT_ID/my-image"
