

steps:
  - name: 'ubuntu'
    args: ['ls', '-l', '/workspace']
  - name: 'ubuntu'
    args: ['ls', '-l', '/workspace/website-DogeLovesHipster-1']
  # Define your build steps here
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "--no-cache"
      - "-t"
      - 'gcr.io/$PROJECT_ID/my-image:$SHORT_SHA'  # Push the image with the "latest" tag
      - "./website-DogeLovesHipster-1"

  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/my-image:$SHORT_SHA"  # Push the image with the "latest" tag

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - "gcr.io/$PROJECT_ID/my-image:$SHORT_SHA"  # Reference the image with the "latest" tag
